version: '3.8'

services:
  shree-varshaa-web:
    build: .
    container_name: shree-varshaa-container
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - shop-network

networks:
  shop-network:
